package com.ddairy.eyebrows.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7a5900)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffde9c)
val md_theme_light_onPrimaryContainer = Color(0xFF261900)
val md_theme_light_secondary = Color(0xFF6b5c3f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf5e0bb)
val md_theme_light_onSecondaryContainer = Color(0xFF241a04)
val md_theme_light_tertiary = Color(0xFF4a6546)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFccebc4)
val md_theme_light_onTertiaryContainer = Color(0xFF082008)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf8)
val md_theme_light_onBackground = Color(0xFF1e1b16)
val md_theme_light_surface = Color(0xFFfffbf8)
val md_theme_light_onSurface = Color(0xFF1e1b16)
val md_theme_light_surfaceVariant = Color(0xFFede1cf)
val md_theme_light_onSurfaceVariant = Color(0xFF4d4639)
val md_theme_light_outline = Color(0xFF7f7667)
val md_theme_light_inverseOnSurface = Color(0xFFf7efe6)
val md_theme_light_inverseSurface = Color(0xFF34302a)

val md_theme_dark_primary = Color(0xFFf8bd2a)
val md_theme_dark_onPrimary = Color(0xFF402d00)
val md_theme_dark_primaryContainer = Color(0xFF5c4200)
val md_theme_dark_onPrimaryContainer = Color(0xFFffde9c)
val md_theme_dark_secondary = Color(0xFFd8c4a0)
val md_theme_dark_onSecondary = Color(0xFF3b2f16)
val md_theme_dark_secondaryContainer = Color(0xFF52452a)
val md_theme_dark_onSecondaryContainer = Color(0xFFf5e0bb)
val md_theme_dark_tertiary = Color(0xFFb0cfa9)
val md_theme_dark_onTertiary = Color(0xFF1e361c)
val md_theme_dark_tertiaryContainer = Color(0xFF334d30)
val md_theme_dark_onTertiaryContainer = Color(0xFFccebc4)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1b16)
val md_theme_dark_onBackground = Color(0xFFe9e1d8)
val md_theme_dark_surface = Color(0xFF1e1b16)
val md_theme_dark_onSurface = Color(0xFFe9e1d8)
val md_theme_dark_surfaceVariant = Color(0xFF4d4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFd0c5b4)
val md_theme_dark_outline = Color(0xFF998f7f)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1b16)
val md_theme_dark_inverseSurface = Color(0xFFe9e1d8)

val seed = Color(0xFFfbc02d)
val error = Color(0xFFba1b1b)